### ISSUE TITLE
hardcoded pixdim[0] doesn't follow standard

### ISSUE THREAD

**Issue by pieper** [freesurfer/surfa#4]
While debugging a different issue I noticed that the output of SynthStrip, which uses surfa internally, wrote out a qform that was inconsistent with the sform (the head was upside-down when using the qform orientation).

This line hardcodes `pixdim[0]` to be `1`:
https://github.com/freesurfer/surfa/blob/master/surfa/io/framed.py#L486

But the [nifti header documentation says](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h):

>   N.B.: Method 2 uses a factor 'qfac' which is either -1 or 1; qfac is
>    stored in the otherwise unused pixdim[0]. 

It would be better to write the identical transform to both the qform and sform since it's not always known which one the receiving software will use.

**Comment by ahoopes** [comment]
Sorry for only getting to this now, but thanks for tracking things down. This has caused problems elsewhere as well. Chalk it up to hacky coding on my part that I forgot to revisit. I'm fairly confident that this quick fix 968327bc0cfe3b372c3eb8984b17c76cdf608867 should ensure that qfac, qform, and sform are properly set now, but I'll do some more testing on it before we release a new surfa version and synthstrip release. Hopefully won't take more than a day or two.

**Comment by ahoopes** [comment]
Just [released a new synthstrip version](https://github.com/freesurfer/freesurfer/issues/1025) that includes this fix.
